[build]
  # Directory to publish (relative to root of repo)
  publish = "."
  
  # Build command (not needed for static HTML)
  command = ""

[build.environment]
  # Optional: Set any environment variables here

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Optional: Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000"

# Cache images for longer
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
